### PR TITLE
Fix nullable custom properties in PHP 8.0

### LINKED ISSUE #1114: TypeError: enum_exists(): Argument #1 ($enum) must be of type string, null given, called in /.../ResolveForPropertyValueAction.php on line 37
**Describe the bug**
After updating to `v4.7.0`, I now receive the below exception in several areas of my application:

```
TypeError: enum_exists(): Argument #1 ($enum) must be of type string, null given, called in /.../ResolveForPropertyValueAction.php on line 37
```

**To Reproduce**
Create a new activity log with a `null` value for a custom property.

**Expected behavior**

This is a new exception. I'm assuming this is due to a custom property being set to `null` in my application:

https://github.com/spatie/laravel-activitylog/blob/89aee268578c0f996e2a1cea99f94fa7e1dd25e7/src/ActivityLogger.php#L106

**Versions (please complete the following information)**
- PHP: 8.0
- Database: MySQL 8.0
- Laravel: 9.39
- Package: 4.7.0

**Stack Trace**
```
TypeError: enum_exists(): Argument #1 ($enum) must be of type string, null given, called in .../vendor/spatie/laravel-activitylog/src/Actions/ResolveForPropertyValueAction.php on line 37
.../vendor/symfony/polyfill-php81/bootstrap.php:27
.../vendor/spatie/laravel-activitylog/src/Actions/ResolveForPropertyValueAction.php:37
.../vendor/spatie/laravel-activitylog/src/Actions/ResolveForPropertyValueAction.php:22
.../vendor/spatie/laravel-activitylog/src/ActivityLogger.php:106
.../vendor/laravel/framework/src/Illuminate/Collections/Arr.php:560
.../vendor/laravel/framework/src/Illuminate/Collections/Collection.php:719
.../vendor/spatie/laravel-activitylog/src/ActivityLogger.php:106
```

### PR DESCRIPTION
**Pull request by stevebauman**
Closes #1114

### CODE REVIEW

File: src/Actions/ResolveForPropertyValueAction.php [hunk 1]
```diff
@@ -34,6 +34,6 @@ protected function isValueAnEnum($value): bool
 
         $enumNamespace = is_object($value) ? get_class($value) : $value;
 
-        return ! is_array($value) && enum_exists($enumNamespace);
+        return ! is_array($value) && enum_exists((string) $enumNamespace);
```
Comment (Gummibeer) [inline src/Actions/ResolveForPropertyValueAction.php:37]: Doing an explicit string check should be better. As it could also be a boolean or whatever else we have.
```suggestion
        return ! is_array($value) && is_string($enumNamespace) && enum_exists($enumNamespace);
```

**Review by Gummibeer — APPROVED** [review]
Thanks for that fix! 🎉

**Comment by Gummibeer** [comment]
https://github.com/spatie/laravel-activitylog/releases/tag/4.7.1
